### ISSUE TITLE
[feat] Refactor Ansible roles for better shareability

### ISSUE THREAD

**Issue by DocN0** [pascaliske/infrastructure#380]
hey ! thanks a lot for this repo ! 

Gladly would like to set up the k3s cluster so however I have the problem that when I execute:
`$ yarn run play playbooks/provision.yml`

of course the vault can not be unlocked, unfortunately I do not understand the mechanism behind it yet and would like to delete this, but even this brings me hnicht much further, so how do I proceed correctly here?

or what must be changed / or deleted? 
thank you very much!

**Comment by pascaliske** [comment]
Hey, thanks for your feedback! In fact, the Ansible part is very specific to my setup and not as reproducible as I would like it to be - I'm planning to re-work a lot of this stuff.

To use the provision playbook you would need to manually setup your own vault file (`vars/vault.yml`) with your own secrets (just delete the file, create a new empty file and then encrypt/decrypt it using the `yarn run vault:encrypt` & `yarn run vault:decrypt` commands). Additionally it could be necessary to skip some of the tasks/roles due to hardware/setup incompatibilities...

Simplest solution for you would be to rely on some kind of official K3s Ansible role (e.g. https://github.com/k3s-io/k3s-ansible) because those are meant to be used from others. You could still use the other GitOps part (`cluster/**`) from this repository afterwards if you want. 🙂

**Comment by pascaliske** [comment]
@DocN0 If you still want to use my Ansible code - I refactored it a bit. You can create your own initial vault file using the `task vault:setup` command (one-time). Please keep in mind that the roles are still very specific to my setup (node count/names/labels/taints, communication via tailscale, etc.) 🙂
